
FROM golang:1.21

# Set destination for COPY
WORKDIR /myapp

RUN go version

# Copy go.mod and execute to download Go modules
COPY go.mod go.sum ./
RUN go mod download

COPY AUTHORS.md ./


COPY LINKS.md ./

COPY *.go ./

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o /my-go-app


EXPOSE 77

# Run
CMD [ "/my-go-app" ]