version: "3.8"

name: my-wise-word-compose

services:
  app:
    container_name: go_service
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    env_file:
      - .env
    build:
      context: ./go_service
      dockerfile: dockerfile
    ports:
      - 9911:78
    networks:
      - netwwc
    depends_on:
      postgreedb:
        condition: service_healthy

  postgreedb:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_NAME=${DB_NAME}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - volwwc:/var/lib/postgresql/data
    networks:
      - netwwc
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  volwwc:

networks:
  netwwc:
    driver: bridge
